ciudad_cambiar:
    path: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }
    requirements:
        ciudad: .+

ciudades_recientes:
    path:    /{ciudad}/recientes.{_format}
    defaults: { _controller: CiudadBundle:Default:recientes, _format: html }   
    requirements:
        _format: html|rss     
            
