backend_portada:
    path: /
    defaults: { _controller: BackendBundle:Oferta:index }    

backend_ciudad_cambiar:
    path:     /cambiar-a-/{ciudad}
    defaults: { _controller: BackendBundle:Default:ciudadCambiar }
    
# Importar las rutas de la entidad Oferta generadas en el bundle BackendBundle
backendOferta:
    resource: "@BackendBundle/Resources/config/routing/oferta.yml"
    prefix: /oferta
    
# Importar las rutas de la entidad Ciudad generadas en el bundle BackendBundle    
backendCiudad:
    resource: "@BackendBundle/Resources/config/routing/ciudad.yml"
    prefix:   /ciudad    

# Importar las rutas de la entidad Tienda generadas en el bundle BackendBundle
BackendTienda:
    resource: "@BackendBundle/Resources/config/routing/tienda.yml"
    prefix:   /tienda

# Importar las rutas de la entidad Usuario generadas en el bundle BackendBundle
BackendUsuario:
    resource: "@BackendBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario