# usamos prefix para que todas las rutas de usuario contengan .../usuario/... y no tener que reseñarlo en cada ruta de routing.yml del bundle
usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

# gestión de páginas estáticas
#ej ruta http://localhost/Cupon/web/app_dev.php/sitio/ayuda
pagina_estatica:
    path: /sitio/{pagina}/
    defaults: { _controller:OfertaBundle:Sitio:estatica}
# otra opción para gestionar páginas estáticas mediante la creación y enlace a un archivo app/config/routing_paginas.yml
#ej ruta http://localhost/Cupon/web/app_dev.php/pagina/ayuda    
_paginas_estaticas:
    resource: routing_paginas.yml
    prefix: /pagina
    defaults: { _controller:FrameworkBundle:Template:template}    

# ruta a la página principal.
portada:
    path: /{ciudad}
    defaults: {_controller:OfertaBundle:Default:portada, ciudad: 'madrid'}
# Esta ruta se redirigirá a portada en el controlador porque es obligatorio que aparezca el slash con la ciudad    
#_portada:
#    path: /
#    defaults: {_controller:OfertaBundle:Default:portada}     

#redireccionando a portada desde el propio routing
_portada:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%'}  
    
#ruta detalle de cada oferta
ofertas:
    path:    /{ciudad}/ofertas/{slug}
    defaults:    { _controller: OfertaBundle:Default:oferta }
