pagina_ayuda:
     path: /ayuda/
     defaults: {template:'OfertaBundle:Sitio:ayuda.html.twig'}
pagina_privacidad:
     path: /privacidad/
     defaults: {template:'OfertaBundle:Sitio:privacidad.html.twig'}   
pagina_condiciones:
     path: /condiciones/
     defaults: {template:'OfertaBundle:Sitio:condiciones.html.twig'}   