# Activación de las extensiones Text y Debug de twig    
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }
# Activación de extensiones personales            
    twig.extension.cupon:
        class: Cupon\OfertaBundle\Twig\Extension\CuponExtension
        tags: 
            - { name: twig.extension }

# Cada vez que se produzca un evento kernel.request, ejecutará la clase OfertaBundle/Listener/RequestListener.php-RequestListener para poder devolver formatos pdf
    cupon.ofertabundle.listener.request:
        class: Cupon\OfertaBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }   

# Activar extensión twig para traducir fechas con el método localizeddate          
    intl.twig.extension:
        class: Twig_Extensions_Extension_Intl
        tags: [{ name: 'twig.extension' }]                 
                  
