# en el path no tenemos que poner /usuario/compras porque lo hemos automatizado con la opción prefix en app/config/routing.yml
usuario_compras:
    path:     /compras
    defaults: { _controller: UsuarioBundle:Default:compras }

usuario_login:
    path:     /login
    defaults: { _controller: UsuarioBundle:Default:login }    

usuario_login_check:
    path:     /login_check

usuario_logout:
    path:     /logout
    
usuario_registro:
    path: /registro
    defaults: { _controller: UsuarioBundle:Default:registro }    